# Generated by Django 2.1.2 on 2018-10-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
